baseURL = "http://michail.pw/"
languageCode = "ru-ru"
title = "Michail's blog"
publishDir = "docs"
theme = "hugo-theme-minos"

paginate = 10

[params]
    smartToc = true
    disqusShortname = "xxxxxx"
    googleAnalytics = "UA-3761048-10"