baseURL = "http://mikhail.cz/"
title = "Mikhail Mamaev"
publishDir = "docs"
theme = "hugo-goa"
author = "Mikhail Mamaev" 

paginate = 10

[params]
author = "Mikhail Mamaev"
intro = "Photographer and software engineer"
description = ""
authorimage = "avatar.jpg"
dateformat = "Jan 2, 2006"

[params.social]
github = "nardin"
instagram = "nardinroot"