baseURL = "http://nardin.github.io/blog/"
languageCode = "ru-ru"
title = "Have Space Suit - Will Travel"
publishDir = "docs"
theme = "hugo-theme-minos"

paginate = 10



[params]
    smartToc = true
    disqusShortname = "xxxxxx"
    googleAnalytics = "UA-3761048-10"