baseURL = "http://havespacesuit.ru/"
languageCode = "ru-ru"
title = "Have Space Suit - Will Travel"
publishDir = "docs"
theme = "hugo-theme-my"

paginate = 10

[[menu.main]]
    name = "Прочитанные книги"
    pre = "<i class='fa fa-road'></i>"
    weight = -110
    url = "/book/"

[[menu.main]]
    name = "Обо мне"
    pre = "<i class='fa fa-heart'></i>"
    weight = -100
    identifier = "about"
    url = "/about/"

[params]
    smartToc = true
    disqusShortname = "disqus_f2Xxyvs38m"
    googleAnalytics = "UA-3761048-11"